# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 16:29
from __future__ import unicode_literals

import almacen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='cod_barras',
            field=models.ImageField(blank=True, null=True, upload_to=almacen.models.upload_image_pathb),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='medida',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='proveedor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='ubicacion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='unidad',
            field=models.CharField(max_length=50),
        ),
    ]
